# NOTE: For more details check the link below.
# https://github.com/slsa-framework/oss-na24-slsa-workshop-model-integrity/blob/main/model_signing/readme.md
---
apiVersion: rhtas.redhat.com/v1alpha1
kind: ModelValidation
metadata:
  name: oss-na24-slasa-workshop
spec:
  config:
    # pkiConfig:
    #   certificateAuthority: /path/to/ca.crt
    # privateKeyConfig:
    #   keyPath: /root/pub.key
    sigstoreConfig:
      certificateIdentity: "https://github.com/sigstore/model-validation-operator/.github/workflows/sign-model.yaml@refs/tags/v0.0.2"
      certificateOidcIssuer: "https://token.actions.githubusercontent.com"
  model:
    path: /data
    signaturePath: /data/model.sig
---
apiVersion: v1
kind: Pod
metadata:
  name: whatever-workload
  labels:
    validation.rhtas.redhat.com/ml: "true"
spec:
#  restartPolicy: Never
  containers:
  - name: whatever-workload
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: model-storage
      mountPath: /data
  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: models

